#include "strings.h"

// The status line is narrow, 144 pixels on a Pebble 2, so each language uses the short word it
// would really use for on and off: an/aus, wl./wyl., pa/av, and so on.
static const char *const s_strings[StrLanguageCount][StrCount] = {
  [StrLanguageEnglish] = {
    [StrBpm] = "BPM",
    [StrSearching] = "Searching...",
    [StrLive] = "Live",
    [StrDemo] = "Demo",
    [StrNoSensor] = "No pulse sensor (hold DOWN for demo)",
    [StrNoPermission] = "No health permission",
    [StrVibOn] = "Vib on",
    [StrVibOff] = "Vib off",
    [StrSoundOn] = "Sound on",
    [StrSoundOff] = "Sound off",
    [StrVibrationOn] = "Vibration on",
    [StrVibrationOff] = "Vibration off",
    [StrLightPulse] = "Light: pulse",
    [StrLightFlash] = "Light: flash",
    [StrLightOn] = "Light: on",
    [StrLightNormal] = "Light: normal",
  },
  [StrLanguageGerman] = {
    [StrBpm] = "BPM",
    [StrSearching] = "Suche Puls...",
    [StrLive] = "Live",
    [StrDemo] = "Demo",
    [StrNoSensor] = "Kein Pulssensor (DOWN lang: Demo)",
    [StrNoPermission] = "Keine Health-Freigabe",
    [StrVibOn] = "Vib an",
    [StrVibOff] = "Vib aus",
    [StrSoundOn] = "Ton an",
    [StrSoundOff] = "Ton aus",
    [StrVibrationOn] = "Vibration an",
    [StrVibrationOff] = "Vibration aus",
    [StrLightPulse] = "Licht: Puls",
    [StrLightFlash] = "Licht: Blitz",
    [StrLightOn] = "Licht: an",
    [StrLightNormal] = "Licht: normal",
  },
  [StrLanguageFrench] = {
    [StrBpm] = "BPM",
    [StrSearching] = "Recherche...",
    [StrLive] = "Live",
    [StrDemo] = "Démo",
    [StrNoSensor] = "Pas de capteur (BAS long : démo)",
    [StrNoPermission] = "Accès santé refusé",
    [StrVibOn] = "Vib. on",
    [StrVibOff] = "Vib. off",
    [StrSoundOn] = "Son on",
    [StrSoundOff] = "Son off",
    [StrVibrationOn] = "Vibration on",
    [StrVibrationOff] = "Vibration off",
    [StrLightPulse] = "Lum. : pulsée",
    [StrLightFlash] = "Lum. : flash",
    [StrLightOn] = "Lum. : on",
    [StrLightNormal] = "Lum. : normale",
  },
  [StrLanguageSpanish] = {
    [StrBpm] = "BPM",
    [StrSearching] = "Buscando...",
    [StrLive] = "Live",
    [StrDemo] = "Demo",
    [StrNoSensor] = "Sin sensor (ABAJO largo: demo)",
    [StrNoPermission] = "Sin permiso de salud",
    [StrVibOn] = "Vib. on",
    [StrVibOff] = "Vib. off",
    [StrSoundOn] = "Sonido on",
    [StrSoundOff] = "Sonido off",
    [StrVibrationOn] = "Vibración on",
    [StrVibrationOff] = "Vibración off",
    [StrLightPulse] = "Luz: pulso",
    [StrLightFlash] = "Luz: flash",
    [StrLightOn] = "Luz: on",
    [StrLightNormal] = "Luz: normal",
  },
  [StrLanguageItalian] = {
    [StrBpm] = "BPM",
    [StrSearching] = "Ricerca...",
    [StrLive] = "Live",
    [StrDemo] = "Demo",
    [StrNoSensor] = "Nessun sensore (GIÙ lungo: demo)",
    [StrNoPermission] = "Permesso salute negato",
    [StrVibOn] = "Vib. on",
    [StrVibOff] = "Vib. off",
    [StrSoundOn] = "Suono on",
    [StrSoundOff] = "Suono off",
    [StrVibrationOn] = "Vibrazione on",
    [StrVibrationOff] = "Vibrazione off",
    [StrLightPulse] = "Luce: pulsata",
    [StrLightFlash] = "Luce: flash",
    [StrLightOn] = "Luce: on",
    [StrLightNormal] = "Luce: normale",
  },
  [StrLanguageDutch] = {
    [StrBpm] = "BPM",
    [StrSearching] = "Zoeken...",
    [StrLive] = "Live",
    [StrDemo] = "Demo",
    [StrNoSensor] = "Geen sensor (OMLAAG lang: demo)",
    [StrNoPermission] = "Geen health-toegang",
    [StrVibOn] = "Tril aan",
    [StrVibOff] = "Tril uit",
    [StrSoundOn] = "Geluid aan",
    [StrSoundOff] = "Geluid uit",
    [StrVibrationOn] = "Trilling aan",
    [StrVibrationOff] = "Trilling uit",
    [StrLightPulse] = "Licht: puls",
    [StrLightFlash] = "Licht: flits",
    [StrLightOn] = "Licht: aan",
    [StrLightNormal] = "Licht: normaal",
  },
  [StrLanguagePortuguese] = {
    [StrBpm] = "BPM",
    [StrSearching] = "Procurando...",
    [StrLive] = "Live",
    [StrDemo] = "Demo",
    [StrNoSensor] = "Sem sensor (BAIXO longo: demo)",
    [StrNoPermission] = "Sem permissão de saúde",
    [StrVibOn] = "Vib. on",
    [StrVibOff] = "Vib. off",
    [StrSoundOn] = "Som on",
    [StrSoundOff] = "Som off",
    [StrVibrationOn] = "Vibração on",
    [StrVibrationOff] = "Vibração off",
    [StrLightPulse] = "Luz: pulso",
    [StrLightFlash] = "Luz: flash",
    [StrLightOn] = "Luz: on",
    [StrLightNormal] = "Luz: normal",
  },
  [StrLanguagePolish] = {
    [StrBpm] = "BPM",
    [StrSearching] = "Szukam...",
    [StrLive] = "Live",
    [StrDemo] = "Demo",
    [StrNoSensor] = "Brak czujnika (DÓŁ dłużej: demo)",
    [StrNoPermission] = "Brak dostępu do zdrowia",
    [StrVibOn] = "Wibr. wł.",
    [StrVibOff] = "Wibr. wył.",
    [StrSoundOn] = "Dźwięk wł.",
    [StrSoundOff] = "Dźwięk wył.",
    [StrVibrationOn] = "Wibracja wł.",
    [StrVibrationOff] = "Wibracja wył.",
    [StrLightPulse] = "Światło: puls",
    [StrLightFlash] = "Światło: błysk",
    [StrLightOn] = "Światło: wł.",
    [StrLightNormal] = "Światło: norm.",
  },
  [StrLanguageSwedish] = {
    [StrBpm] = "BPM",
    [StrSearching] = "Söker...",
    [StrLive] = "Live",
    [StrDemo] = "Demo",
    [StrNoSensor] = "Ingen sensor (NED länge: demo)",
    [StrNoPermission] = "Ingen hälsobehörighet",
    [StrVibOn] = "Vib. på",
    [StrVibOff] = "Vib. av",
    [StrSoundOn] = "Ljud på",
    [StrSoundOff] = "Ljud av",
    [StrVibrationOn] = "Vibration på",
    [StrVibrationOff] = "Vibration av",
    [StrLightPulse] = "Ljus: puls",
    [StrLightFlash] = "Ljus: blink",
    [StrLightOn] = "Ljus: på",
    [StrLightNormal] = "Ljus: normalt",
  },
};

static uint8_t s_language = StrLanguageEnglish;

void strings_set_language(uint8_t language) {
  s_language = (language < StrLanguageCount) ? language : StrLanguageEnglish;
}

const char *str(StringId id) {
  if (id >= StrCount) {
    return "";
  }
  const char *text = s_strings[s_language][id];
  return text ? text : s_strings[StrLanguageEnglish][id];
}
