#!/usr/bin/env python3
"""Generate src/c/beep_sample.h, the per-beat monitor beep played on watches with a speaker.

The defaults reproduce the tone of a patient monitor: an 880 Hz fundamental with the second and
third harmonic mixed in at the levels measured from a real monitor recording, 50 ms long, with a
raised-cosine attack and release so the sample starts and ends at zero and cannot click.

    python3 tools/make_beep_sample.py > src/c/beep_sample.h
"""
import argparse
import sys

import numpy as np

parser = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
parser.add_argument("--freq", type=float, default=880.0, help="fundamental in Hz (default 880)")
parser.add_argument("--rate", type=int, default=16000, help="sample rate in Hz (default 16000)")
parser.add_argument("--ms", type=float, default=50.0, help="length in ms (default 50)")
parser.add_argument("--attack-ms", type=float, default=3.0, help="fade in, ms (default 3)")
parser.add_argument("--release-ms", type=float, default=10.0, help="fade out, ms (default 10)")
parser.add_argument("--harmonics", default="1.0,0.55,0.22",
                    help="comma separated amplitudes of the 1st, 2nd, ... harmonic")
parser.add_argument("--peak", type=float, default=0.92, help="peak level, 0..1 (default 0.92)")
parser.add_argument("--tail-ms", type=float, default=0.0,
                    help="silence appended after the tone, ms (default 0). The app plays the "
                         "sample into a stream that carries on with silence by itself, so none is "
                         "needed here; it was useful when the watch closed the speaker after "
                         "every beep.")
args = parser.parse_args()

sr = args.rate
n = int(sr * args.ms / 1000.0)
if n < 2:
    sys.exit("sample is too short")
t = np.arange(n) / sr

sig = np.zeros(n)
amps = [float(a) for a in args.harmonics.split(",")]
for k, amp in enumerate(amps, start=1):
    if k * args.freq * 2 > sr:
        sys.exit("harmonic %d at %.0f Hz exceeds the Nyquist limit of this sample rate"
                 % (k, k * args.freq))
    sig += amp * np.sin(2 * np.pi * k * args.freq * t)

attack = min(int(args.attack_ms * sr / 1000.0), n // 2)
release = min(int(args.release_ms * sr / 1000.0), n // 2)
env = np.ones(n)
if attack:
    env[:attack] = 0.5 - 0.5 * np.cos(np.pi * np.arange(attack) / attack)
if release:
    env[n - release:] = 0.5 + 0.5 * np.cos(np.pi * np.arange(release) / release)
sig *= env

sig /= np.abs(sig).max()
pcm = np.round(sig * args.peak * 32767).astype(np.int16)
pcm[0] = 0
pcm[-1] = 0

tail = int(args.tail_ms * sr / 1000.0)
if tail > 0:
    pcm = np.concatenate([pcm, np.zeros(tail, dtype=np.int16)])
n += tail

midi = int(round(69 + 12 * np.log2(args.freq / 440.0)))
print("/*")
print(" * Monitor beep sample, generated by tools/make_beep_sample.py - do not edit by hand.")
print(" * Included only on watches that have a speaker.")
print(" */")
print("#pragma once")
print("#include <pebble.h>")
print()
print("// %.0f Hz beep, %d Hz / 16-bit mono, %.0f ms of tone plus %.0f ms of silence,"
      % (args.freq, sr, args.ms, args.tail_ms))
print("// harmonics %s." % args.harmonics)
print("// Raised-cosine attack and release keep the sample click-free at both ends.")
print("#define BEEP_SAMPLE_RATE_HZ %d" % sr)
print("#define BEEP_MIDI_NOTE      %d    // the sample plays unshifted at this note" % midi)
print("#define BEEP_LEN_MS         %d    // tone and trailing silence together" %
      round(args.ms + args.tail_ms))
print("static const int16_t s_beep_pcm[%d] = {" % n)
for i in range(0, n, 12):
    print("  " + ", ".join("%6d" % v for v in pcm[i:i + 12]) + ",")
print("};")
